apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - app-deployment.yaml
 - app-hpa.yaml
 - app-service.yaml
 - redis-config.yaml
 - redis-deployment.yaml
 - redis-service.yaml
secretGenerator:
 - name: prod-secrets
   files:
   - podinfoUIColor=secrets/podinfoUIColor.encrypted
