apiVersion: v1
kind: Secret
metadata:
    name: prod-secrets
data:
    podinfoUIColor: ENC[AES256_GCM,data:/CHeWX2wSo1edXvh,iv:Ie1PSkmr22h7A7HHp+M9Lr59fUyAMiORLTbIrvmFSwc=,tag:F/Hf6QzsFoS20bHi4PzZ6Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:457472006214:key/f0b5d296-5e36-4d68-8dad-3abe58ccdb8c
          created_at: "2022-06-20T05:32:08Z"
          enc: AQICAHhAl0F3/YYjKxiWrLJMJIat5KkzMk7P6zjrrzwMC8J0dwHKUh7ycKb8TSE4VhLvAf2mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj6M+8319pdp/GokKAgEQgDuoK/+OEnl1rueiOOs26HkQO5Z+RSL/5ZKZ5CEysinV+VXnw0Jqj2S5Fgj9kxFa6Y3Dp/EYBuXfJ05T9g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-20T05:32:08Z"
    mac: ENC[AES256_GCM,data:NeYoocSpi1Emc1p5bMIvtttrsyBgGV4VHGw2XA41R9JG+chM069oUmrHGLcS9YHrRHNtEaXKsCj06DyJEzGrY37wZ16ExHY03nruFKPXXTDzr3qNtVffbHg+a7UG2U8hzxerBB+SNd444J0Gaw5aLASXGYi/TJ0d09ZlbEgVKvo=,iv:ymo0W4chJvqIZbwj6r/QXNqPe+PQksDvSVdJqB1q41Q=,tag:rv3cmalEkwKnRh4kpAuS1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
